### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property '_c' of undefined

### ISSUE THREAD

**Issue by johnenrick** [nikitasnv/vue-resizable#14]
I am using Vue 3, and I get an error. Is Vue 3 already supported?

**Comment by hacklover** [comment]
I migrated vue-resizable to Vue 3, @nikitasnv can I open a pull request?  
[https://github.com/hacklover/vue-resizable](https://github.com/hacklover/vue-resizable)

PS: unit tests aren't working for now

**Comment by nikitasnv** [comment]
Yes, it works with vue 3 now

**Comment by hacklover** [comment]
Oh, awesome! Thank you.

You may want to declare also the "emits" property [like this](https://github.com/hacklover/vue-resizable/commit/902cb0d8fe78e85cb35a99eed18ecfd9fe94123f), now Vue 3 requires it

**Comment by nikitasnv** [comment]
@hacklover thanks, will add it soon

**Comment by RuchitaPatel-J2** [comment]
in vue3 I am still getting this error . Is it work for vue3 or not ?.
