### ISSUE TITLE
 (0 , t.withScopeId) is not a function

### ISSUE THREAD

**Issue by SidSid1986** [nikitasnv/vue-resizable#19]
(0 , t.withScopeId) is not a function

**Comment by zerr0o** [comment]
Same error on electron !

**Comment by marinaselyakh** [comment]
@SidSid1986 @zerr0o I use  "vue-resizable": "1.1.3" version, it helped

**Comment by zerr0o** [comment]
@marinaselyakh thanks for the reply ! i figured it out.
@SidSid1986 I was using vue 2, last vue-resizable release is only for vue 3.
just upgrade your vue version or downgrade vue-resizable ;)
It works perfectly btw

**Comment by nikitasnv** [comment]
Yeah. Component versions 2+ use vue 3. I'm not sure older versions will be supported, so you should upgrade to vue 3 if you can.
