### ISSUE TITLE
when two resizable component is inside each other.

### ISSUE THREAD

**Issue by Nehasoni988** [nikitasnv/vue-resizable#22]
Hello @nikitasnv 

I am using two vue-resizable inside each other which means I want to drag parent as well as child.
The only problem I am facing is when I am dragging the child element the parent is also dragging.
I have created the example- https://codesandbox.io/s/vue-template-forked-7kyi9?file=/src/App.vue

Is there any way that If a child is dragging up then the parent can not drag?

**Comment by nikitasnv** [comment]
@Nehasoni988 Fixed in 0954269.

**Comment by nikitasnv** [comment]
@Nehasoni988 check #19

**Comment by Nehasoni988** [comment]
Ohh, it means the new version won't work in vue2?
