### ISSUE TITLE
vue 3

### ISSUE THREAD

**Issue by adnan-sahin** [nikitasnv/vue-resizable#36]
Hi, is this package supported in vue 3? 
When I tried in vue 3, I got error.
if you relpy me as soon as possible, It will be great
Thank you

**Comment by nikitasnv** [comment]
Yes, you can use it with vue3

**Comment by adnan-sahin** [comment]
> Yes, you can use it with vue3

Thank you so much.

**Comment by adnan-sahin** [comment]
> Yes, you can use it with vue3

I tried it in vue 3. I got error. you can see below
<img width="723" alt="image" src="https://user-images.githubusercontent.com/6214217/161516422-d39b410b-658d-4713-8ce8-1d1eedfb0bf0.png">

**Comment by calebwaldner** [comment]
Same ^

**Comment by nikitasnv** [comment]
Try updated version
