### ISSUE TITLE
How can I get the element where dropped end?

### ISSUE THREAD

**Issue by hasib-workspacify** [nikitasnv/vue-resizable#39]
In a Loop, I'm using multiple VueResizable components. if I drop one component to another component I want to get the both component info. How can I do that?

**Comment by nikitasnv** [comment]
Check data payload in event, Added "cmp" value with component

**Comment by hasib-devs** [comment]
Could you please give me an example?

**Comment by hasib-devs** [comment]
I want to get the element where I drop. It could be the closest div or another Resizeable component.
