### ISSUE TITLE
in flex,some props isn't work

### ISSUE THREAD

**Issue by hqzh** [nikitasnv/vue-resizable#4]
[online](https://codepen.io/hqzh/pen/vYLbgbN)
right maxWidth is invalid,left is  out of control

**Comment by nikitasnv** [comment]
In flex box you do not need to change left offset of the component. I added a prop to disable the required attribute: **disabled-attributes**.
Check [updated pen](https://codepen.io/nikitasnv/pen/gOPVqGr).

**Comment by hqzh** [comment]
it's worked,thank you so much!
