### ISSUE TITLE
Web API Animation

### ISSUE THREAD

**Issue by Slender1808** [nikitasnv/vue-resizable#6]
I wanted to let this suggestion use Web API Animation responsible was to make the transformation of the possession of the elements.
https://developer.mozilla.org/en-US/docs/Web/API/Animation
https://developer.mozilla.org/en-US/docs/Web/API/Animation/replaceState#Examples

**Comment by nikitasnv** [comment]
I see no need to add this. You can add a listener to the component by yourself.
