### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [nikitasnv/vue-resizable#8]
Are all those dependencies non-dev dependencies?
I'm guessing none of those are and vue could be a pear dependency
```
"dependencies": {
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "cross-env": "^7.0.2",
    "vue": "^2.6.11",
    "webpack": "^4.43.0"
  },
```

**Comment by nikitasnv** [comment]
True, didn't change it from start. Updated in beb82aadb0c2d21c5f9847625d511a4dd356c9cb
