### ISSUE TITLE
attributes are set when they shouldn't

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [nikitasnv/vue-resizable#9]
When i'm only activating `'r'` I would expect that only the width of an html element would change.
But the left, top and height are also set. 
I've even tried this:
```
<vue-resizable class="folders-wrapper d-flex" :width="300" :active="['r']" fit-parent :max-width="500" :min-width="100" :disable-attributes="['l', 't', 'h']">
```
But then the attributes are changed as wel.

The downside of this is that i can't set an element to have a `height: auto`

**Comment by ricardovanlaarhoven** [comment]
Workaround:
add a `height: auto!important`

**Comment by nikitasnv** [comment]
Can you reproduce issue via codepen?

**Comment by ricardovanlaarhoven** [comment]
Take in mind that there are more reasons why the height could change but that this is an excellent example why.

https://codepen.io/ricardovanlaarhoven/pen/OJNEpYo

In my opinion when there are no directions of the height that are resizeable the height should not be set to that element.
When only setting `:active="['r']"` height could not be touched, so it should not be set.

**Comment by nikitasnv** [comment]
Updated in 45fb317b1227fb9e540bb37d1eb98137d33599ab. Use disableAttributes property.
